FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/urls.py
"""Definiuje wzorce adresów URL dla learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Strona główna.
    path('', views.index, name='index'),
    # Wyświetlenie wszystkich tematów.
    path('topics/', views.topics, name='topics'),
    # Strona szczegółowa dotycząca pojedynczego tematu.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """Temat poznawany przez użytkownika."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        """Zwraca reprezentację modelu w postaci ciągu tekstowego."""
        return self.text

class Entry(models.Model):
    """Konkretne informacje o postępie w nauce."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
 
    def __str__(self):
        """Zwraca reprezentację modelu w postaci ciągu tekstowego."""
        return f"{self.text[:50]}..."

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/views.py
from django.shortcuts import render

from .models import Topic

def index(request):
    """Strona główna dla aplikacji Learning Log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Wyświetlenie wszystkich tematów."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Wyświetla pojedynczy temat i wszystkie powiązane z nim wpisy."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/templates/learning_logs/base.html
<p>
  <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
  <a href="{% url 'learning_logs:topics' %}">Tematy</a>
</p>

{% block content %}{% endblock content %}

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Learning Log pomaga w monitorowaniu postępów w nauce podczas poznawania dowolnego tematu.</p>
{% endblock content %}

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

  <p>Temat: {{ topic }}</p>

  <p>Wpisy:</p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.date_added|date:'d M Y H:i' }}</p>
      <p>{{ entry.text|linebreaks }}</p>
    </li>
  {% empty %}
    <li>Nie ma jeszcze żadnego wpisu.</li>
  {% endfor %}
  </ul>

{% endblock content %}

FoxDot/PCC2-kody/Rozdzial18/building_additional_pages/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Tematy</p>

  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>Nie został jeszcze dodany żaden temat.</li>
    {% endfor %}
  </ul>

{% endblock content %}